### ISSUE TITLE
DOC: Fix typo in Heston equation

### ISSUE THREAD

**Issue by simaki** [pfnet-research/pfhedge#184]
dt is missing in the second equation. Appreciate a PR fixing this!

<img width="902" alt="Screen Shot 2021-08-12 at 21 40 30" src="https://user-images.githubusercontent.com/24503967/129198378-32a9909b-3aff-4fb4-b6ad-3b345ecbe08b.png">

**Comment by kadatatlukishore** [comment]
Hello @simaki would like to do this. Could you please brief this up for me ?

**Comment by simaki** [comment]
Sure, thank you a lot!

The thing is, docstring of generate_heston should be fixed because dt is missing in the first term of the left-hand side of the second equation. 

https://en.wikipedia.org/wiki/Heston_model#Basic_Heston_model

**Comment by kadatatlukishore** [comment]
Thanks a lot @simaki , Please review the PR and let me know if the change is not correct

**Comment by simaki** [comment]
Thanks a lot!!
I appreciate it if you could also resolve other good-first-issue's because I'm looking to merge this along with other small fixes/enhancements.
