### ISSUE TITLE
Type incompatible in time-series generation and autogreek

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#189]
I think this is a very minor issue.

The example of autogreek allowed putting `torch.Tensor` with autograd into `init_state`.
https://github.com/masanorihirano/pfhedge/blob/develop/pfhedge/autogreek.py#L54-L71

Through `Hedger.price`, `Hedger.compute_pnl`, and [`derivertive.simulate`](https://github.com/masanorihirano/pfhedge/blob/develop/pfhedge/nn/modules/hedger.py#L170), the underlying asset accept the init_state, such as [`BrownianStock`](https://github.com/masanorihirano/pfhedge/blob/68527b0536038cc24e46117d67acedf7347a5278/pfhedge/instruments/primary/brownian.py#L79).

In the underlying assets, `init_state` was handled as `Optional[tuple]`, such as:
https://github.com/masanorihirano/pfhedge/blob/develop/pfhedge/instruments/primary/brownian.py#L55-L62
https://github.com/masanorihirano/pfhedge/blob/develop/pfhedge/instruments/primary/brownian.py#L108-L116

However, in `stochastic` modules, these are handled as float, such as:
https://github.com/masanorihirano/pfhedge/blob/develop/pfhedge/stochastic/brownian.py#L7-L15

Fortunately, this doesn't cause any issue now.
However, this is very misleading and can cause an issue when we make our own time series.
(Actually, I had.)

`init_state` can accept multiple initial states and the number is not consistent.
Thus, it is reasonable that these underlying assets accept it as `Optional[tuple]`.
But, considering the case it includes some tensors with grad, it should be `Optional[tuple[torch.Tensor]]`, and some functions in stochastic models should also accept torch.Tensor.

But, I understand this change causes wide modifications. Thus, it has to be thought carefully even though this is a minor issue.

**Comment by simaki** [comment]
Thank you for reporting! I agree that all functions generating stochastic time-series should receive their initial states as `init_state: Tuple[Union[float, Tensor], ...]`, rather than `init_value: float`, `init_value: Union[float, Tensor]`, or `init_state: Tuple[float, ...]`. (Is my understanding correct?) I appreciate a PR fixing it!

**Comment by masanorihirano** [comment]
Basically, your understanding is correct.

However, this is not only typing problem.
When we assumed the logarithm of init state in the future implementation of other time-series generators, the situation could be complicated.
Although torch tensor has log method has a log method, float doesn't.
But, if we use math.log or wrapping by torch.Tensor, it could cause gradient disconnection.

**Comment by simaki** [comment]
Yeah accepting `Union[float, Tensor]` requires additional care. Something like `init_state = tuple(map(torch.as_tensor, init_state))` would allow us to make use of retained gradients and a bunch of Tensor methods. Thank you for clarifying!

**Comment by simaki** [comment]
I'm gonna work on it! 👍 👍 👍 

>all functions generating stochastic time-series should receive their initial states as init_state: Tuple[Union[float, Tensor], ...], rather than init_value: float, init_value: Union[float, Tensor], or init_state: Tuple[float, ...].
