### ISSUE TITLE
Attribute of __vesions__

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#222]
pfhedge doesn't have `__version__` attribute

**Comment by simaki** [comment]
Yeah, I understand that would be useful given such an "agile" situation. Thank you for pointing it out.
I will try but cannot commit to that. Could you use `pip show pfhedge | grep Version` or https://github.com/python-poetry/poetry/issues/273#issuecomment-401983643 ?

**Comment by masanorihirano** [comment]
OK. I got it. No problem. Thank you for suggesting of workaround．

**Comment by simaki** [comment]
Closing for now. Please do not hesitate to reopen 👍
