### ISSUE TITLE
Inappropriate instance generation of Features

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#311]
In the preamble of the feature getter, features are defined as instances.

https://github.com/pfnet-research/pfhedge/blob/97fab4435e47f7a832f2416fbdb7d8b855ebb241/pfhedge/features/_getter.py#L16-L27

This is very harmful if multiple hedgers are used at the same time, especially, multi-processing with multiple GPUs.
It is because these features have derivatives and hedgers as parameters.
Thus, unintentional overwrite from other hedgers causes unexpected bugs.

I understand this implementation was done for avoiding making many instances of them.
However, these instances have to correspond to both hedgers and derivatives one-on-one.
Currently, I always coded like `copy.deepcopy(gget_feature(x)).of(derivative, hedger)`, and successfully avoided this issue.
But, the current implementation seems harmful rather than beneficial.
So, I highly suggest the change of implementation.

**Comment by masanorihirano** [comment]
I added a fix example I imagine.
Please also refer to it.

**Comment by simaki** [comment]
That's so true.
Thank you for sharing the issue and solution!
