### ISSUE TITLE
Default parameter for init_state in heston process

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#395]
https://pfnet-research.github.io/pfhedge/stochastic.html#pfhedge.stochastic.generate_heston

I think (1.0, sigma**2) is better for init_state.
Thus, how about changing the default of init_state to None and calculating them in this method.

**Comment by simaki** [comment]
Sounds good! I think theta would be the best.

**Comment by masanorihirano** [comment]
Oh, you're right.

But, I think the best setting is sigma**2 = theta = V(0).
It seems a little complicated.
What's the best solution for it?

**Comment by simaki** [comment]
Only V(0) = theta would suffice? I may be missing something and don't see a reason to impose sigma**2 = theta. sigma is the volatility of V and not necessarily assumed to be the value of V itself.

By the way, generate_cir may also need a similar update.

**Comment by masanorihirano** [comment]
I was wrong.

I was confused that sigma means volatility, but correctly it is vol. of vol.

Thus, Only V(0) = theta is OK.

**Comment by simaki** [comment]
I will accept a pr!

**Comment by masanorihirano** [comment]
I'll make a pr later. (It could be next week.)
