### ISSUE TITLE
gamma support for put option in European option

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#411]
Why don't you support gamma for european put option?
The calculation seems the same as call one.

https://github.com/pfnet-research/pfhedge/blob/4d7ff173995e0795942bc6ec55f3fdc5bfb7a5f1/pfhedge/nn/modules/bs/european.py#L140-L149

**Comment by simaki** [comment]
Sure we can remove that ValueError. PR appreciated!
