### ISSUE TITLE
bugs in greeks calculation?

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#413]
I have checked if greeks calculation is correct. But, vega seems incorrect.

https://svc.qri.jp/jpx/nkopm/
![image](https://user-images.githubusercontent.com/14543048/146501596-77db219e-cef9-4746-8441-8ec313c15f4f.png)

```
BSEuropeanOption(call=True, strike=28500).delta(log_moneyness=torch.tensor(28535/28500).log(), time_to_maturity=torch.tensor(17/252), volatility=torch.tensor(0.1817))
# tensor(0.5198)
BSEuropeanOption(call=True, strike=28500).gamma(log_moneyness=torch.tensor(28535/28500).log(), time_to_maturity=torch.tensor(17/252), volatility=torch.tensor(0.1817))
# tensor(0.0003)
BSEuropeanOption(call=True, strike=28500).vega(log_moneyness=torch.tensor(28535/28500).log(), time_to_maturity=torch.tensor(17/252), volatility=torch.tensor(0.1817))
# tensor(2953.0981)

BSEuropeanOption(call=False, strike=28500).delta(log_moneyness=torch.tensor(28535/28500).log(), time_to_maturity=torch.tensor(17/252), volatility=torch.tensor(0.1738))
# tensor(-0.4802)
BSEuropeanOption(call=False, strike=28500).gamma(log_moneyness=torch.tensor(28535/28500).log(), time_to_maturity=torch.tensor(17/252), volatility=torch.tensor(0.1738))
# tensor(0.0003)
BSEuropeanOption(call=False, strike=28500).vega(log_moneyness=torch.tensor(28535/28500).log(), time_to_maturity=torch.tensor(17/252), volatility=torch.tensor(0.1738))
# tensor(2953.0750)
```

only vega is calculated via the autogreek module. Of course, one solution is overriding vega method in `BSEuropeanOption` class.
However, I think this issue is not just an issue in `BSEuropeanOption` class.

Of course, I think I can implement vega method in `BSEuropeanOption` class as PR.
But, unfortunantally, I haven't found what is the cause in autogrek module because I have never use this module.

**Comment by simaki** [comment]
I'm not sure there's a bug: Autogreek almost agrees with the BS formula.

```py
import torch
from pfhedge.nn import BSEuropeanOption
from pfhedge import autogreek
from pfhedge.nn.functional import npdf
from pfhedge.nn.functional import d1


s = 28535
k = 28500
t = 17 / 252
v = 0.1817
lm = torch.tensor(s / k).log()


x = autogreek.vega(
    BSEuropeanOption(call=True, strike=k).price,
    volatility=torch.tensor(v),
    log_moneyness=lm,
    time_to_maturity=torch.tensor(t),
)
print(x)
# tensor(2953.0981)

x = s * npdf(d1(lm, t, v)) * torch.tensor(t).sqrt()
print(x)
# tensor(2953.0979)
```

Vega computed by svc.qri.jp seems the sensitivity to 1% vola change = 100 times ours definition.
What is weird is that there's still several percent of error.

**Comment by simaki** [comment]
dividend?

**Comment by simaki** [comment]
>Of course, I think I can implement vega method in BSEuropeanOption class as PR.

Whatever the case this is awesome for performance 👍

**Comment by masanorihirano** [comment]
> 28535 is the future price right?
Yes.

> Vega computed by svc.qri.jp seems the sensitivity to 1% vola change = 1/100 times ours definition.
OK. I got it.

I have set t = 17/252, but, it could be 17/243 or 18/243 because JPX has only 243 business days in this year, and the option calculation of this page could be based on the setting of the beginning of the trading day. 
Because vega is very sensitive, these difference in setting or digit precision could cause the current difference.

**Comment by masanorihirano** [comment]
results using autogreek were the same as the one using my BS implementation. Thus, this issue was just my misunderstanding of the sensitivity order.
Just for your information, I found that the risk-free-rate of the real market also has an effect on vega via BS d1/d2. (This is not matter in pfhedge)
