### ISSUE TITLE
Primary spot typing

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#530]
https://github.com/pfnet-research/pfhedge/blob/5c71d6f65d57c75fb7ce917704f11057874082c8/pfhedge/instruments/primary/base.py#L145-L155

Before running a simulation, Primary.spot could return None. The typing should be different.

**Comment by masanorihirano** [comment]
Why it is important is some method assumed that it doesn't return None and it could undesirably cause uncontrolled error like:
https://github.com/pfnet-research/pfhedge/blob/5c71d6f65d57c75fb7ce917704f11057874082c8/pfhedge/instruments/primary/brownian.py#L87-L93

**Comment by simaki** [comment]
Appreciate good catch, solved by https://github.com/pfnet-research/pfhedge/pull/533.
get_buffer returns Tensor if the buffer exists, otherwise raise an error. None would never be returned.

**Comment by simaki** [comment]
Fixed by #533
