### ISSUE TITLE
gpu bug in functional.py 

### ISSUE THREAD

**Issue by zxem** [pfnet-research/pfhedge#589]
Hi, 

in line 506, a new tensor c is created without assigning to the same device as input tensors. 
   c = torch.tensor(cost).unsqueeze(0).unsqueeze(-1)

The example notebook fails when running with GPU. 

Regards

**Comment by masanorihirano** [comment]
This seems the same as #576 . Isn't it?

**Comment by zxem** [comment]
yes. possible. 
Is this project still actively developed? I am happy to make a contribution.

**Comment by masanorihirano** [comment]
This issue is merged to #567
