### ISSUE TITLE
Calculate the derivative of the hedging model over the hedging instruments.

### ISSUE THREAD

**Issue by XiaoqiDong96** [pfnet-research/pfhedge#590]
Hi developers,

Suppose the model is u and the hedging instruments are in s. I am wondering how to get the result of du/ds.

**Comment by masanorihirano** [comment]
Do you mean the delta of the portfolio? It can be calculated by accumulating the results from [nn.BlackSholes](https://pfnet-research.github.io/pfhedge/generated/pfhedge.nn.BlackScholes.html)
