### ISSUE TITLE
How to extract the optimal hedging paths (post model fitting)?

### ISSUE THREAD

**Issue by XiaoqiDong96** [pfnet-research/pfhedge#591]
Hi developers:

I am using pfhedge library to do some simple examples, and I want to look at the optimal hedging paths after I trained the model. I used "pos=hedger.compute_hedge(derivative).squeeze(1)". 
Is this correct?

Thanks

**Comment by masanorihirano** [comment]
I think so, but .squeeze(1) seems not necessary. See: https://pfnet-research.github.io/pfhedge/generated/pfhedge.nn.Hedger.html?highlight=compute_hedge#pfhedge.nn.Hedger.compute_hedge
